### ISSUE TITLE
I can't set up correct paths

### ISSUE THREAD

**Issue by Madscuttle** [DiekoMA/Flow.Launcher.Plugin.Godot#1]
Extension don't seems to work but i could set up wrong paths can u tell me how correct path will be i tried thoes:
D:/Godot/Godot_v4.2.1-stable_mono_win64/Godot_v4.2.1-stable_mono_win64.exe
"D:\Godot\Godot_v4.2.1-stable_mono_win64\Godot_v4.2.1-stable_mono_win64.exe"
D:\Godot\Godot_v4.2.1-stable_mono_win64\Godot_v4.2.1-stable_mono_win64.exe
"D:\Godot\Godot_v4.2.1-stable_mono_win64"
D:\Godot\Godot_v4.2.1-stable_mono_win64

**Comment by DiekoMA** [comment]
It should be D:\Godot\Godot_v4.2.1-stable_mono_win64\Godot_v4.2.1-stable_mono_win64.exe
