### ISSUE TITLE
support for multiple project paths

### ISSUE THREAD

**Issue by mowfax** [DiekoMA/Flow.Launcher.Plugin.Godot#2]
My projects are set up in a way that they are not in a single project folder.
Would it be possible for you to allow an arbitrary number of project paths?
A possible solution could be a list where paths can be added and deleted.
Another way I can think of would be reading the projects.cfg in the engine config folder.

**Comment by DiekoMA** [comment]
Thanks for posting an issue, I've added those changes and pushed and update.
